### ISSUE TITLE
How to convert collected libero trajs to RLDS format?

### ISSUE THREAD

**Issue by zhan72** [aiming-lab/GRAPE#4]
Thanks for your excellent work!

I follow the instruction in Dataset part and have collected the success/fail trajs in Libero.
But I find that the trajs are npy and the RLDS format is needed to finetune the openvla.
Can you give me some advice to convert the npy to RLDS format?

Best

**Comment by zzj1111** [comment]
Hi Haozhan! The next step is to use dataset construction scripts to convert npy to RLDS, which I mentioned in #3. We will release it ASAP.

**Comment by CostaliyA** [comment]
> Hi Haozhan! The next step is to use dataset construction scripts to convert npy to RLDS, which I mentioned in [#3](https://github.com/aiming-lab/GRAPE/issues/3). We will release it ASAP.

Great work! I have found some issues with the current script and have already submitted a PR. I hope it can be merged :D
